---@meta

-- Type annotations only - never executed. The declarations below define real
-- globals and library functions with empty bodies, so loading this file at
-- runtime would replace working functions with stubs rather than declare them.
-- It lives outside lua/ so the game cannot reach it; this is the backstop.
error("wire.lua contains type annotations only and must never be executed")

-- Wiremod is an optional runtime dependency and is not on workspace.library, so the
-- surface Sonic-Screwdriver touches is declared here instead.

---@param ent Entity
---@param oname string
---@param value any
function Wire_TriggerOutput(ent, oname, value) end

-- gmod_wire_keypad builds its members at runtime, so glua_ls can't see them: `SetDisplayText`
-- is a NetworkVar accessor generated by `self:NetworkVar("String", 0, "DisplayText")` in
-- SetupDataTables, and `CurrentNum` is a plain field the keypad logic assigns. Declare the
-- members Sonic-Screwdriver casts to (sv_wiremod.lua).
---@class gmod_wire_keypad : Entity
---@field SetDisplayText fun(self: self, text: string)
---@field CurrentNum number