---@meta

-- gmod_wire_keypad builds its members at runtime, so glua_ls can't see them: `SetDisplayText`
-- is a NetworkVar accessor generated by `self:NetworkVar("String", 0, "DisplayText")` in
-- SetupDataTables, and `CurrentNum` is a plain field the keypad logic assigns. Declare the
-- members Sonic-Screwdriver casts to (sv_wiremod.lua).
---@class gmod_wire_keypad : Entity
---@field SetDisplayText fun(self: self, text: string)
---@field CurrentNum number
